<a href="https://colab.research.google.com/github/Rey-uni/Vje-be/blob/main/AI_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
1

1

In [ ]:
type(1) # vrsta varijable ili ceg ne - intager

int

In [ ]:
type(1.3) # decimalni

float

In [ ]:
type("Andrej")

str

In [ ]:
"apple"

'apple'

In [ ]:
True

True

In [ ]:
False

False

In [ ]:
3<5 #boolean logika, 0 ili 1 su vrijednosti F i T

True

dictionaries {} - dodajemo osobu i npr. smjer ili godine, pozovem ime i izbaci se ostalo list [] tuple ()

In [ ]:
t=[1,2,3]

In [ ]:
type(t)

list

In [ ]:
t

[1, 2, 3]

In [ ]:
plants = {"apple": "a fruit", "banana": "a herb"}

In [ ]:
type(plants
     )

dict

In [ ]:
plants

{'apple': 'a fruit', 'banana': 'a herb'}

In [ ]:
import pandas as pd



In [ ]:
pd.DataFrame(plants,[0,1]) #indeksiranje prema broju od 0

apple  banana
0  a fruit  a herb
1  a fruit  a herb

In [ ]:
squares= [1,4,9,16,25]

In [ ]:
squares[4]

25

In [ ]:
squares[-2]

16

In [ ]:
squares[:]

[1, 4, 9, 16, 25]

In [ ]:
squares[1:]

[4, 9, 16, 25]

In [ ]:
squares + [36,49,64,81,100]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [ ]:
sq2= squares + [36,49,64,81,100]

In [ ]:
sq2

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [ ]:
animals = ["dogs", "cats", "birds"]

In [ ]:
len(sq2[:5]) #duljina do pola :5 duljina do 20% je :2 vjv

5

In [ ]:
letters = ["a", "b", "c", "d"]

In [ ]:
letters[1:2]= [1,2,3,4,5]
letters  #umjesto b ce umetnuti to

['a', 1, 2, 3, 4, 5, 'c', 'd']

In [ ]:
abs(-10)


10

In [ ]:
import operator

In [ ]:
operator.add(1,3) #ista stvar

4

In [ ]:
operator.sub(1,10) #1-10

-9

In [ ]:
operator.eq(1,10) #1-10

False

In [ ]:
print(1)

1


In [ ]:
print("Michael", "is", "helping")

Michael is helping


In [ ]:
print("Michael"+" "+"is"+" "+"helping")

Michael is helping


In [ ]:
print(sq2[2:5])

[9, 16, 25]


In [ ]:
None

In [ ]:
type(None
    )

NoneType

FUNKCIJE

In [ ]:
def FUNKCIJA(x):
  "OPIS FUNKCIJE"
  RESULTS = x+2
  return RESULTS

In [ ]:
FUNKCIJA(5)

7

In [ ]:
type(FUNKCIJA
    )

function

In [ ]:
import math

In [ ]:
def ph(ch):
  "iznačun ph na temelju c H, vraća ph"
  ph_value= -math.log10(ch)
  return ph_value
ph(4)

-0.6020599913279624

In [ ]:
from numpy import number
def task(x,y):
  "definicija"
  print("this is the log10 of x", math.log10(x))
  print("this is the log10 of y", math.log10(y))
  new_number = math.log10(x) + math.log(y)
  print("sum below:")
  return new_number

In [ ]:
task(1,2)

this is the log10 of x 0.0
this is the log10 of y 0.3010299956639812
sum below:


0.6931471805599453

In [ ]:
# = i ==

In [ ]:
1==1

True

In [ ]:
k=(1,2,3)

In [ ]:
type(k)

tuple

In [ ]:
cp1="tomo"
cp2="marija"
cp1,cp2

('tomo', 'marija')

In [ ]:
w=20
h=5*4

In [ ]:
w==h

True

In [ ]:
cp1==cp2

False

In [ ]:
cp1!=cp2

True

In [ ]:
# is, is not

In [ ]:
5 is 4

<>:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
/tmp/ipython-input-171648558.py:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
  5 is 4


False

In [ ]:
cp1 is not cp2

True

In [ ]:
squares

[1, 4, 9, 16, 25]

In [ ]:
squares.append(36)

In [ ]:
squares

[1, 4, 9, 16, 25, 36]

In [ ]:
squares2= squares + [36]
squares2

[1, 4, 9, 16, 25, 36, 36]

In [ ]:
last_list = squares.copy() #kopiras listu
last_list

[1, 4, 9, 16, 25, 36]

In [ ]:
last_list.append(10)
last_list

[1, 4, 9, 16, 25, 36, 10]

In [ ]:
print("Participants in the course", cp1, "and", cp2)

Participants in the course tomo and marija


In [ ]:
print("Participants in the course were %s and %s.")

Participants in the course were %s and %s.


In [ ]:
print("Participants in the course were %s and %s."
  %(cp1,cp2))

Participants in the course were tomo and marija.


In [ ]:
sample = "u552"
conc = 0.002

print("In a sample %s we found %s mg/L of drugs" %(sample,conc))

In a sample u552 we found 0.002 mg/L of drugs


In [ ]:
print(f"In a sample {sample} we found {conc} mg/L of drugs.")

In a sample u552 we found 0.002 mg/L of drugs.


In [ ]:
# vittičasta je shift + option + š i đ
# uglata option š i đ

In [ ]:
def bmi(w,h):
  bmi = w/ h ** 2
  return bmi

In [ ]:
bmi(96,1.92)

26.041666666666668

In [ ]:
def diluter(c1=0.5 ,v1=1, v2=2):
  "Calculatim dilution rturns c2"
  c2= c1*v1/v2
  return c2

In [ ]:
#U praksi se ne definira bas gore sto već dolje

In [ ]:
diluter()

0.25

In [ ]:
help(diluter)

Help on function diluter in module __main__:

diluter(c1=0.5, v1=1, v2=2)
    Calculatim dilution rturns c2



In [ ]:
diluter(2) #računa da je 2 prvi argument

1.0

In [ ]:
diluter(2,1,3)

0.6666666666666666

In [ ]:
def factor_corrections(c,f=1):
  conc=c*f
  return conc

In [ ]:
factor_corrections(1,2)

2

In [ ]:
def do_something_else(a=1,b=2,c=3):
  return (a,b,c)

In [ ]:
do_something_else()

(1, 2, 3)

In [ ]:
do_something_else(10, 10)

(10, 10, 3)

In [ ]:
do_something_else(5,5,c=2)

(5, 5, 2)

In [ ]:
def suma(a,b):
    return a+b

def adding_3rd(a,b,c):
    return suma(a,b) +c

adding_3rd(1,2,3)

6

In [ ]:
# for

In [ ]:
my_friends = ["Michael", "Tomo", "Maria", "Petar"]

In [ ]:
for x in my_friends:
  print(x)

Michael
Tomo
Maria
Petar


In [ ]:
weights = [80, 90, 110, 70]
heights = [1.8, 2, 1.6, 1.5]

for x, friend in enumerate(my_friends): #enumerate je bitan za to da izvlačimo iz drugih lista isto tim redom
  bmi_person=bmi(weights[x],heights[x])

print(f'{friend} has the bmi of {bmi_person}.')
#samo zadnjeg izbacuje

Petar has the bmi of 31.11111111111111.


In [ ]:
weights = [80, 90, 110, 70]
heights = [1.8, 2, 1.6, 1.5]

for x, friend in enumerate(my_friends): #enumerate je bitan za to da izvlačimo iz drugih lista isto tim redom
  bmi_person=bmi(weights[x],heights[x])

  print(f'{friend} has the bmi of {bmi_person}.')
  #samo zadnjeg izbacuje

Michael has the bmi of 24.691358024691358.
Tomo has the bmi of 22.5.
Maria has the bmi of 42.96874999999999.
Petar has the bmi of 31.11111111111111.


In [ ]:
bmi_person

31.11111111111111

In [ ]:
squares

[1, 4, 9, 16, 25, 36]

In [ ]:
for x in squares:
  print("Element is %s" %x)

Element is 1
Element is 4
Element is 9
Element is 16
Element is 25
Element is 36


In [ ]:
for number in squares:
  print(number)

1
4
9
16
25
36


In [ ]:
course_participants =[cp1,cp2]
course_participants

['tomo', 'marija']

In [ ]:
for name in course_participants:
  print(name)

tomo
marija


In [ ]:
for pos in range(len(course_participants)):
  print (pos)

0
1


In [ ]:
import math


In [ ]:
for number in squares:
  sq_root = math.sqrt(number)
  print(sq_root)

1.0
2.0
3.0
4.0
5.0
6.0


In [ ]:
# if else

In [ ]:
1 <= 2

True

In [ ]:
if 1==1:
  print ("yes")
  print( "Da")
  print ("Ja")
# ako nije istina ne radi ništa

yes
Da
Ja


In [ ]:
1==2
# ako nije istina reci ce

False

In [ ]:
cp1= "Mila"
cp2= "Marko"

In [ ]:
if cp1 == cp2:
  print("Da")
else:
  print("Ne")

Ne


In [ ]:
def chech_gender_by_name(name):
  if name[-1]=="a":
    gender = "female"
  elif name[-1]=="o":
    gender = "male"
  else:
    gender = "unknown"
  return gender

In [ ]:
chech_gender_by_name("Lano")

'male'

In [ ]:
import math as m

In [ ]:
def ph(c):
  return -m.log10(c)

In [ ]:
ph(10)

-1.0

In [ ]:
def ph_evaluator(c=0.001):
  ph_value = ph(c)
  if ph_value < 7:
    decision = "kiselo"
  else:
    decision = "lužnato"
  return decision

ph_evaluator(0.1)

'kiselo'

In [ ]:
def ph_evaluator(c=0.001):

  if ph(c) < 7: #zovemo postojeću funkciju:
    return "kiselo"
  else:
    return "lužnato"

conc_list = [0.001, 0.01, 0.1, 1, 10]
for solution in conc_list:
  print(ph_evaluator(solution))

kiselo
kiselo
kiselo
kiselo
kiselo


In [ ]:
def test_if_else(a,b):
  "a, b su argumenti - vraća a < b ili a nije < b"
  if a > b:
    print(a,">",b)
  else:
    print("%d is not > %d" %(a,b))

In [ ]:
help(test_if_else)

Help on function test_if_else in module __main__:

test_if_else(a, b)
    a, b su argumenti - vraća a < b ili a nije < b



In [ ]:
test_if_else(2,6)

2 is not > 6


In [ ]:
def rectangle_area(a,b):
  "dokumentacija"
  A=a*b
  if a==b:
      print("kvadrat")
  else:
      print("pravokutnik")
  return A

In [ ]:
rectangle_area(2,3)

pravokutnik


6

In [ ]:
for letter in [1,2,3]:
  print("broj:", letter)

broj: 1
broj: 2
broj: 3


In [ ]:
povrsina = rectangle_area(5,4)

pravokutnik


In [ ]:
povrsina

20

In [ ]:
a = [4,5,6]
n = [1,2,3]
x = [a,n]
x

[[4, 5, 6], [1, 2, 3]]

In [ ]:
import numpy as np

In [ ]:
nums1 = [1,2,3,4,5]
nums1

[1, 2, 3, 4, 5]

In [ ]:
nums2 = np.array(nums1) #ako bi dodali slovo a bi to bilo string
nums2

array([1, 2, 3, 4, 5])

In [ ]:
type(nums1), type(nums2)

(list, numpy.ndarray)

In [ ]:
max(nums1), min(nums1)

(5, 1)

In [ ]:
np.max(nums1), np.min(nums1)

(np.int64(5), np.int64(1))

In [ ]:
x1 = np.array([1.3,0,2])
x1

array([1.3, 0. , 2. ])

In [ ]:
x2 = np.array([1,0,2])
x2

array([1, 0, 2])

In [ ]:
type(x1), type(x2)

(numpy.ndarray, numpy.ndarray)

In [ ]:
x1.dtype, x2.dtype

(dtype('float64'), dtype('int64'))

In [ ]:
x2 = np.arange(20,50,2)
x2

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [ ]:
np.linspace(10,20,10,endpoint=True) #uključuje 20

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [ ]:
nule = np.zeros((5,3)) #prvo se navodi red pa stupac
nule.shape

(5, 3)

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
x4 = np.random.random((3,10))
x4

array([[0.59450908, 0.32557645, 0.94522701, 0.08550961, 0.1654936 ,
        0.89747575, 0.2414205 , 0.86281301, 0.57849123, 0.57515823],
       [0.55782185, 0.75665509, 0.46382775, 0.58090661, 0.58227242,
        0.00805867, 0.78185232, 0.5413819 , 0.1975303 , 0.16571066],
       [0.98154963, 0.67275422, 0.74225837, 0.62005167, 0.02121574,
        0.43776505, 0.9148809 , 0.06882048, 0.97093954, 0.07335261]])

In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame(x4)

0         1         2         3         4         5         6  \
0  0.594509  0.325576  0.945227  0.085510  0.165494  0.897476  0.241420   
1  0.557822  0.756655  0.463828  0.580907  0.582272  0.008059  0.781852   
2  0.981550  0.672754  0.742258  0.620052  0.021216  0.437765  0.914881   

          7         8         9  
0  0.862813  0.578491  0.575158  
1  0.541382  0.197530  0.165711  
2  0.068820  0.970940  0.073353

In [ ]:
x4.dtype

dtype('float64')

In [ ]:
x4.shape

(3, 10)

In [ ]:
x4.reshape(10,3)

array([[0.59450908, 0.32557645, 0.94522701],
       [0.08550961, 0.1654936 , 0.89747575],
       [0.2414205 , 0.86281301, 0.57849123],
       [0.57515823, 0.55782185, 0.75665509],
       [0.46382775, 0.58090661, 0.58227242],
       [0.00805867, 0.78185232, 0.5413819 ],
       [0.1975303 , 0.16571066, 0.98154963],
       [0.67275422, 0.74225837, 0.62005167],
       [0.02121574, 0.43776505, 0.9148809 ],
       [0.06882048, 0.97093954, 0.07335261]])

In [ ]:
np.arange(2,20).reshape(2,3,3).T

array([[[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]],

       [[ 4, 13],
        [ 7, 16],
        [10, 19]]])

In [ ]:
I = np.eye(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])