<a href="https://colab.research.google.com/github/Rey-uni/Vje-be/blob/main/AI_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Jako bitno za ispit!

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('https://raw.githubusercontent.com/bio-chem-info/python_course/refs/heads/main/preprocess_data.csv')
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
#transpose
#točkica je pipeline operator - "gradimo zmiju"
a= dataset.tail(2).T
b= dataset.T.tail(2)
a

8        9
Country    Germany   France
Age           50.0     37.0
Salary     83000.0  67000.0
Purchased       No      Yes

In [ ]:
dataset.head(2)

Country   Age   Salary Purchased
0  France  44.0  72000.0        No
1   Spain  27.0  48000.0       Yes

In [ ]:
X = dataset.iloc[:,:-1]
Y = dataset.iloc[:,-1]
X, Y

(   Country   Age   Salary
 0   France  44.0  72000.0
 1    Spain  27.0  48000.0
 2  Germany  30.0  54000.0
 3    Spain  38.0  61000.0
 4  Germany  40.0      NaN
 5   France  35.0  58000.0
 6    Spain   NaN  52000.0
 7   France  48.0  79000.0
 8  Germany  50.0  83000.0
 9   France  37.0  67000.0,
 0     No
 1    Yes
 2     No
 3     No
 4    Yes
 5    Yes
 6     No
 7    Yes
 8     No
 9    Yes
 Name: Purchased, dtype: object)

In [ ]:
#ako pita za statistiku vjv misli deskriptivnu idk
X.describe()

Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [ ]:
X.isna().sum()

Country    0
Age        1
Salary     1
dtype: int64

Missing data

In [ ]:
X.fillna(0)
#X.fillna(0, inplace=True) ako želimo da ostane u memoriji

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      0.0
5   France  35.0  58000.0
6    Spain   0.0  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [ ]:
# objekt koji je kopija neke obrade
X1= X.fillna(0)
X1

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      0.0
5   France  35.0  58000.0
6    Spain   0.0  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [ ]:
#X.fillna(-99)

In [ ]:
from sklearn.impute import SimpleImputer #module importamo iz sklearna
imputer = SimpleImputer(missing_values=np.nan,
                        strategy="median") #naš recept kako popuniti prazne vrijednosti
imputer.fit(X[["Age", "Salary"]]) #fit
imputer.statistics_ # ovdje je naučio medijane naših stupaca prije zamjene i ispisao nam medijane

array([3.8e+01, 6.1e+04])

In [ ]:
X[["Age", "Salary"]].median() #uglata zagrada u indeksiranju uglata kao pišem listu

Age          38.0
Salary    61000.0
dtype: float64

In [ ]:
#fit - učenje
#transform -
X_imputed = imputer.transform(X[["Age", "Salary"]])
X_imputed

array([[4.4e+01, 7.2e+04],
       [2.7e+01, 4.8e+04],
       [3.0e+01, 5.4e+04],
       [3.8e+01, 6.1e+04],
       [4.0e+01, 6.1e+04],
       [3.5e+01, 5.8e+04],
       [3.8e+01, 5.2e+04],
       [4.8e+01, 7.9e+04],
       [5.0e+01, 8.3e+04],
       [3.7e+01, 6.7e+04]])

In [ ]:
type(X_imputed)

numpy.ndarray

In [ ]:
#BITNO - konverzija matrice u df - data, columns, indexi
X_imp = pd.DataFrame(X_imputed,
                     columns = ["Age", "Salary"],
                     index=X.index)
X_imp

Age   Salary
0  44.0  72000.0
1  27.0  48000.0
2  30.0  54000.0
3  38.0  61000.0
4  40.0  61000.0
5  35.0  58000.0
6  38.0  52000.0
7  48.0  79000.0
8  50.0  83000.0
9  37.0  67000.0

In [ ]:
X_imp.median()

Age          38.0
Salary    61000.0
dtype: float64

In [ ]:
#prvo sam prebacio nan u -999
imputer = SimpleImputer(missing_values=np.nan,
                        strategy="constant",fill_value= -999)
imputer.fit(X[["Age", "Salary"]]) #fit
nn = imputer.transform(X[["Age", "Salary"]])
nnn = pd.DataFrame(nn,
                     columns = ["Age", "Salary"],
                     index=X.index)
imputer = SimpleImputer(missing_values=-999,
                        strategy="median")
imputer.fit(nnn[["Age", "Salary"]]) #fit
nn = imputer.transform(nnn[["Age", "Salary"]])
nn

array([[4.4e+01, 7.2e+04],
       [2.7e+01, 4.8e+04],
       [3.0e+01, 5.4e+04],
       [3.8e+01, 6.1e+04],
       [4.0e+01, 6.1e+04],
       [3.5e+01, 5.8e+04],
       [3.8e+01, 5.2e+04],
       [4.8e+01, 7.9e+04],
       [5.0e+01, 8.3e+04],
       [3.7e+01, 6.7e+04]])

Encoding the independent variable

In [ ]:
X

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [ ]:
X_encoded = pd.get_dummies(X, columns=["Country"], drop_first=True)
X_encoded

Age   Salary  Country_Germany  Country_Spain
0  44.0  72000.0            False          False
1  27.0  48000.0            False           True
2  30.0  54000.0             True          False
3  38.0  61000.0            False           True
4  40.0      NaN             True          False
5  35.0  58000.0            False          False
6   NaN  52000.0            False           True
7  48.0  79000.0            False          False
8  50.0  83000.0             True          False
9  37.0  67000.0            False          False

In [ ]:
X_encoded = pd.get_dummies(X, columns=["Country"])
X_encoded

Age   Salary  Country_France  Country_Germany  Country_Spain
0  44.0  72000.0            True            False          False
1  27.0  48000.0           False            False           True
2  30.0  54000.0           False             True          False
3  38.0  61000.0           False            False           True
4  40.0      NaN           False             True          False
5  35.0  58000.0            True            False          False
6   NaN  52000.0           False            False           True
7  48.0  79000.0            True            False          False
8  50.0  83000.0           False             True          False
9  37.0  67000.0            True            False          False

In [ ]:
#BITNO - replace ide riječnik - key value paths?
X_encoded = X_encoded.replace({True:1,False:0})
X_encoded

/tmp/ipython-input-1370646532.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X_encoded = X_encoded.replace({True:1,False:0})


Age   Salary  Country_France  Country_Germany  Country_Spain
0  44.0  72000.0               1                0              0
1  27.0  48000.0               0                0              1
2  30.0  54000.0               0                1              0
3  38.0  61000.0               0                0              1
4  40.0      NaN               0                1              0
5  35.0  58000.0               1                0              0
6   NaN  52000.0               0                0              1
7  48.0  79000.0               1                0              0
8  50.0  83000.0               0                1              0
9  37.0  67000.0               1                0              0

In [ ]:
#y stupac s 0 i 1
X_encoded = pd.get_dummies(X, columns=["Country"])
X_encoded

Age   Salary  Country_France  Country_Germany  Country_Spain
0  44.0  72000.0            True            False          False
1  27.0  48000.0           False            False           True
2  30.0  54000.0           False             True          False
3  38.0  61000.0           False            False           True
4  40.0      NaN           False             True          False
5  35.0  58000.0            True            False          False
6   NaN  52000.0           False            False           True
7  48.0  79000.0            True            False          False
8  50.0  83000.0           False             True          False
9  37.0  67000.0            True            False          False

In [ ]:
y_encoded = pd.get_dummies(Y)
y_encoded

No    Yes
0   True  False
1  False   True
2   True  False
3   True  False
4  False   True
5  False   True
6   True  False
7  False   True
8   True  False
9  False   True

In [ ]:
Y_encodedd = y_encoded.replace({True:1,False:0}, inplace=True)
Y_encodedd
#Y_encodedd.name("Purchase")

/tmp/ipython-input-3966193166.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  Y_encodedd = y_encoded.replace({True:1,False:0}, inplace=True)


Splitting the dataset in Training and Test set
---
regresija i klasifikacija (tjedni trudnoce, tumor da ne)
validacija - testing set



In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_encoded,
                                                    y_encoded,
                                                    test_size=0.25,
                                                    random_state = 1) #kad ponovno pokrećemo kod da možemo replicirati pseudo random je

In [ ]:
print(X_train)

    Age   Salary  Country_France  Country_Germany  Country_Spain
4  40.0      NaN           False             True          False
0  44.0  72000.0            True            False          False
3  38.0  61000.0           False            False           True
1  27.0  48000.0           False            False           True
7  48.0  79000.0            True            False          False
8  50.0  83000.0           False             True          False
5  35.0  58000.0            True            False          False


In [ ]:
print(X_test)

    Age   Salary  Country_France  Country_Germany  Country_Spain
2  30.0  54000.0           False             True          False
9  37.0  67000.0            True            False          False
6   NaN  52000.0           False            False           True


Feature scaling

In [ ]:
X_train.describe()

Age        Salary
count   7.000000      6.000000
mean   40.285714  66833.333333
std     7.931252  13437.509690
min    27.000000  48000.000000
25%    36.500000  58750.000000
50%    40.000000  66500.000000
75%    46.000000  77250.000000
max    50.000000  83000.000000

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc

StandardScaler()

In [ ]:
#sc.mean_
#error jer nije ništa učio

In [ ]:
X_train_sc = sc.fit(X_train) #uči
sc.mean_, sc.scale_ # dijeli s N (računa kao da je populacija)

(array([4.02857143e+01, 6.68333333e+04, 4.28571429e-01, 2.85714286e-01,
        2.85714286e-01]),
 array([7.34291273e+00, 1.22667120e+04, 4.94871659e-01, 4.51753951e-01,
        4.51753951e-01]))

In [ ]:
X_train.std(ddof=0) #ručno - DIJELI S N-1 (aproksimiramo populaciju) - dodavanjem ddof smanjujemo degrees of freedom na 0 i dobijemo isto kao onaj skejler

Age                    7.342913
Salary             12266.711956
Country_France         0.494872
Country_Germany        0.451754
Country_Spain          0.451754
dtype: float64

In [ ]:
X_train_sc = sc.fit_transform(X_train) #uči i primjenjuje odjednom
X_test_sc = sc.transform(X_test)

In [ ]:
X_train_sc = pd.DataFrame(X_train_sc, columns=X_train.columns, index=X_train.index )
X_train_sc.describe() #i godine i plaća je skalirana na neku kao normalnu distribuciju - maksimalno u ovako skaliranim tablicama je +/-3 jer 3 s.d.

Age        Salary  Country_France  Country_Germany  \
count  7.000000e+00  6.000000e+00    7.000000e+00     7.000000e+00   
mean   1.427430e-16  4.070818e-16    3.172066e-17     3.172066e-17   
std    1.080123e+00  1.095445e+00    1.080123e+00     1.080123e+00   
min   -1.809325e+00 -1.535320e+00   -8.660254e-01    -6.324555e-01   
25%   -5.155603e-01 -6.589650e-01   -8.660254e-01    -6.324555e-01   
50%   -3.891021e-02 -2.717381e-02   -8.660254e-01    -6.324555e-01   
75%    7.782042e-01  8.491816e-01    1.154701e+00     4.743416e-01   
max    1.322947e+00  1.317930e+00    1.154701e+00     1.581139e+00   

       Country_Spain  
count   7.000000e+00  
mean    3.172066e-17  
std     1.080123e+00  
min    -6.324555e-01  
25%    -6.324555e-01  
50%    -6.324555e-01  
75%     4.743416e-01  
max     1.581139e+00

In [ ]:
X_train.describe()

Age        Salary
count   7.000000      6.000000
mean   40.285714  66833.333333
std     7.931252  13437.509690
min    27.000000  48000.000000
25%    36.500000  58750.000000
50%    40.000000  66500.000000
75%    46.000000  77250.000000
max    50.000000  83000.000000

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scm = MinMaxScaler()
scm
X_train_scm = scm.fit_transform(X_train) #uči i primjenjuje odjednom
X_test_scm = scm.transform(X_test)
X_train_scm = pd.DataFrame(X_train_scm, columns=X_train.columns, index=X_train.index )
X_train_scm.describe() #on si računa između 0 do 1 - maks postaje 1 min 0 zbog formule koja je x-x(min)/x(max)-x(min)

Age    Salary  Country_France  Country_Germany  Country_Spain
count  7.000000  6.000000        7.000000         7.000000       7.000000
mean   0.577640  0.538095        0.428571         0.285714       0.285714
std    0.344837  0.383929        0.534522         0.487950       0.487950
min    0.000000  0.000000        0.000000         0.000000       0.000000
25%    0.413043  0.307143        0.000000         0.000000       0.000000
50%    0.565217  0.528571        0.000000         0.000000       0.000000
75%    0.826087  0.835714        1.000000         0.500000       0.500000
max    1.000000  1.000000        1.000000         1.000000       1.000000